services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - ./mongodb:/data/db
    user: "1000:1000"
    networks:
      - backend
    restart: always

networks:
  backend:
