services:
  mongodb:
    image: mongo:9.0.2-noble
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
